export default [
    "Australia",
    "España",
    "Alemania",
    "Brasil",
    "Argentina",
    "Perú",
    "Arabia Saudita",
    "Corea del Sur",
    "Panamá",
    "Marruecos",
    "Japón",
    "Nigeria",
    "Serbia",
    "Irán",
    "Senegal",
    "Egipto",
    "Túnez",
    "Suecia",
    "Costa Rica",
    "Islandia",
    "Dinamarca",
    "Croacia",
    "Uruguay",
    "México",
    "Colombia",
    "Portugal",
    "Inglaterra",
    "Suiza",
    "Rusia",
    "Francia",
    "Polonia",
    "Bélgica"]